FROM node:20-alpine

RUN mkdir -p /opt/nuxt-app
ARG NODE_ENV=development

WORKDIR /opt/nuxt-app
COPY package.json yarn.lock[t] ./
ENV PATH /opt/nuxt-app/node_modules/.bin:$PATH
COPY . .

RUN yarn install
RUN ls -la node_modules/

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

EXPOSE 3000

CMD ["yarn", "dev"]
